version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: ./cargo/fdw_kafka_manager/Dockerfile
    command: python /cargo/fdw_kafka_manager/fdw_kafka_manager.py
    environment:
      CARGO_CONFIG_PATH: '/cargo/configs/config.ini'
    networks:
      - cargo_network
    volumes:
      - /home/cargo/configs:/cargo/configs
networks:
  cfs3_network:
    driver: bridge
